# Generated by Django 3.0.4 on 2020-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('type', models.CharField(default='', max_length=25)),
                ('mode', models.CharField(default='', max_length=25)),
                ('parameter', models.CharField(default='', max_length=25)),
                ('value', models.CharField(default='', max_length=25)),
                ('threshold_up', models.CharField(default='', max_length=25)),
                ('threshold_down', models.CharField(default='', max_length=25)),
                ('currentState', models.CharField(default='', max_length=25)),
                ('desireState', models.CharField(default='', max_length=25)),
                ('connect', models.CharField(default='', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
