# Generated by Django 3.0.4 on 2020-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='mode',
            new_name='currentMode',
        ),
        migrations.AddField(
            model_name='device',
            name='desireMode',
            field=models.CharField(default='', max_length=25),
        ),
    ]
